package com.fredrik.mapProject.gameRunDomain;

public enum Terrain {

    DEEP_WATER,
    COASTAL_WATER,
    LOWLAND_TUNDRA,
    HIGHLANDS_TUNDRA,
    COLD_DESERT,
    COLD_DESERT_HILLS,
    TEMPERATE_LOWLANDS_PLAINS,
    TEMPERATE_FOREST,
    HIGHLAND_HILLS,
    TEMPERATE_HIGHLAND_FOREST,
    TEMPERATE_RAINFOREST,
    TEMPERATE_HIGHLAND_RAINFOREST,
    HOT_DESERT,
    HOT_DESERT_HILLS,
    HOT_STEPPE,
    HOT_STEPPE_HILLS,
    TROPICAL_SAVANNA,
    TROPICAL_SAVANNA_HILLS,
    TROPICAL_RAINFOREST,
    TROPICAL_RAINFOREST_HILLS,
    GLACIER,
    GLACIAL_HEIGHTS,
    MOUNTAINS;

}

